"""empty message

Revision ID: 35d1992ab795
Revises: 5e4599b69a6d
Create Date: 2020-03-28 23:11:34.951873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d1992ab795'
down_revision = '5e4599b69a6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('locked_sub', sa.ARRAY(sa.Boolean(), dimensions=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_sub')
    # ### end Alembic commands ###
