"""empty message

Revision ID: 5e4599b69a6d
Revises: a93befdedbf2
Create Date: 2020-03-28 04:19:44.907071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e4599b69a6d'
down_revision = 'a93befdedbf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('module', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('completed', sa.ARRAY(sa.Boolean(), dimensions=5), nullable=True))
    op.add_column('users', sa.Column('hascomments', sa.ARRAY(sa.Boolean(), dimensions=5), nullable=True))
    op.add_column('users', sa.Column('locked', sa.ARRAY(sa.Boolean(), dimensions=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked')
    op.drop_column('users', 'hascomments')
    op.drop_column('users', 'completed')
    op.drop_table('comments')
    # ### end Alembic commands ###
