"""empty message

Revision ID: 67794b6448fd
Revises: b3bb85d7bd82
Create Date: 2020-03-29 16:14:17.756640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67794b6448fd'
down_revision = 'b3bb85d7bd82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('module', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('graded', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submissions')
    # ### end Alembic commands ###
