"""empty message

Revision ID: 945eaac76999
Revises: 67794b6448fd
Create Date: 2020-03-31 20:48:08.207697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '945eaac76999'
down_revision = '67794b6448fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('module', sa.String(), nullable=True),
    sa.Column('response', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('current_element', sa.ARRAY(sa.Integer(), dimensions=2), nullable=True))
    op.drop_column('users', 'current_module')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_module', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'current_element')
    op.drop_table('responses')
    op.drop_table('announcements')
    # ### end Alembic commands ###
