"""empty message

Revision ID: a4f390c12b5a
Revises: 945eaac76999
Create Date: 2020-03-31 21:17:37.602431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4f390c12b5a'
down_revision = '945eaac76999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responses', sa.Column('responses', sa.ARRAY(sa.String(), dimensions=1), nullable=True))
    op.add_column('responses', sa.Column('submodule', sa.Integer(), nullable=True))
    op.drop_column('responses', 'response')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responses', sa.Column('response', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('responses', 'submodule')
    op.drop_column('responses', 'responses')
    # ### end Alembic commands ###
