"""empty message

Revision ID: b07fb22529e1
Revises: c21cb6e9c373
Create Date: 2020-04-01 03:11:25.166865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b07fb22529e1'
down_revision = 'c21cb6e9c373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('grader', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'grader')
    # ### end Alembic commands ###
