"""empty message

Revision ID: b3bb85d7bd82
Revises: 35d1992ab795
Create Date: 2020-03-29 01:20:45.558225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3bb85d7bd82'
down_revision = '35d1992ab795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_module', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_module')
    # ### end Alembic commands ###
